// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackupSystemInfo.proto

package com.thed.zephyr.capture.util.backup;

public final class BackupSystemInfoBuffer {
  private BackupSystemInfoBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BackupSystemInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string dataVersion = 1;
    /**
     * <code>required string dataVersion = 1;</code>
     */
    boolean hasDataVersion();
    /**
     * <code>required string dataVersion = 1;</code>
     */
    String getDataVersion();
    /**
     * <code>required string dataVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getDataVersionBytes();

    // required string createDate = 2;
    /**
     * <code>required string createDate = 2;</code>
     */
    boolean hasCreateDate();
    /**
     * <code>required string createDate = 2;</code>
     */
    String getCreateDate();
    /**
     * <code>required string createDate = 2;</code>
     */
    com.google.protobuf.ByteString
        getCreateDateBytes();

    // required string creator = 3;
    /**
     * <code>required string creator = 3;</code>
     */
    boolean hasCreator();
    /**
     * <code>required string creator = 3;</code>
     */
    String getCreator();
    /**
     * <code>required string creator = 3;</code>
     */
    com.google.protobuf.ByteString
        getCreatorBytes();

    // required string numberOfObjects = 4;
    /**
     * <code>required string numberOfObjects = 4;</code>
     */
    boolean hasNumberOfObjects();
    /**
     * <code>required string numberOfObjects = 4;</code>
     */
    String getNumberOfObjects();
    /**
     * <code>required string numberOfObjects = 4;</code>
     */
    com.google.protobuf.ByteString
        getNumberOfObjectsBytes();

    // required bool attachments = 5;
    /**
     * <code>required bool attachments = 5;</code>
     */
    boolean hasAttachments();
    /**
     * <code>required bool attachments = 5;</code>
     */
    boolean getAttachments();

    // optional string comment = 6;
    /**
     * <code>optional string comment = 6;</code>
     */
    boolean hasComment();
    /**
     * <code>optional string comment = 6;</code>
     */
    String getComment();
    /**
     * <code>optional string comment = 6;</code>
     */
    com.google.protobuf.ByteString
        getCommentBytes();

    // required string host = 7;
    /**
     * <code>required string host = 7;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 7;</code>
     */
    String getHost();
    /**
     * <code>required string host = 7;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    // required string ctId = 8;
    /**
     * <code>required string ctId = 8;</code>
     */
    boolean hasCtId();
    /**
     * <code>required string ctId = 8;</code>
     */
    String getCtId();
    /**
     * <code>required string ctId = 8;</code>
     */
    com.google.protobuf.ByteString
        getCtIdBytes();

    // required string backupCheckSum = 9;
    /**
     * <code>required string backupCheckSum = 9;</code>
     */
    boolean hasBackupCheckSum();
    /**
     * <code>required string backupCheckSum = 9;</code>
     */
    String getBackupCheckSum();
    /**
     * <code>required string backupCheckSum = 9;</code>
     */
    com.google.protobuf.ByteString
        getBackupCheckSumBytes();

    // optional string jiraId = 10;
    /**
     * <code>optional string jiraId = 10;</code>
     */
    boolean hasJiraId();
    /**
     * <code>optional string jiraId = 10;</code>
     */
    String getJiraId();
    /**
     * <code>optional string jiraId = 10;</code>
     */
    com.google.protobuf.ByteString
        getJiraIdBytes();
  }
  /**
   * Protobuf type {@code com.thed.zephyr.capture.util.backup.BackupSystemInfo}
   */
  public static final class BackupSystemInfo extends
      com.google.protobuf.GeneratedMessage
      implements BackupSystemInfoOrBuilder {
    // Use BackupSystemInfo.newBuilder() to construct.
    private BackupSystemInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BackupSystemInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BackupSystemInfo defaultInstance;
    public static BackupSystemInfo getDefaultInstance() {
      return defaultInstance;
    }

    public BackupSystemInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BackupSystemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              dataVersion_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              createDate_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              creator_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              numberOfObjects_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              attachments_ = input.readBool();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              comment_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              host_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              ctId_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              backupCheckSum_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              jiraId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.class, com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<BackupSystemInfo> PARSER =
        new com.google.protobuf.AbstractParser<BackupSystemInfo>() {
      public BackupSystemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BackupSystemInfo(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<BackupSystemInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string dataVersion = 1;
    public static final int DATAVERSION_FIELD_NUMBER = 1;
    private Object dataVersion_;
    /**
     * <code>required string dataVersion = 1;</code>
     */
    public boolean hasDataVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string dataVersion = 1;</code>
     */
    public String getDataVersion() {
      Object ref = dataVersion_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          dataVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string dataVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDataVersionBytes() {
      Object ref = dataVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dataVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string createDate = 2;
    public static final int CREATEDATE_FIELD_NUMBER = 2;
    private Object createDate_;
    /**
     * <code>required string createDate = 2;</code>
     */
    public boolean hasCreateDate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string createDate = 2;</code>
     */
    public String getCreateDate() {
      Object ref = createDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          createDate_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string createDate = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCreateDateBytes() {
      Object ref = createDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        createDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string creator = 3;
    public static final int CREATOR_FIELD_NUMBER = 3;
    private Object creator_;
    /**
     * <code>required string creator = 3;</code>
     */
    public boolean hasCreator() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string creator = 3;</code>
     */
    public String getCreator() {
      Object ref = creator_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          creator_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string creator = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCreatorBytes() {
      Object ref = creator_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        creator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string numberOfObjects = 4;
    public static final int NUMBEROFOBJECTS_FIELD_NUMBER = 4;
    private Object numberOfObjects_;
    /**
     * <code>required string numberOfObjects = 4;</code>
     */
    public boolean hasNumberOfObjects() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string numberOfObjects = 4;</code>
     */
    public String getNumberOfObjects() {
      Object ref = numberOfObjects_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          numberOfObjects_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string numberOfObjects = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNumberOfObjectsBytes() {
      Object ref = numberOfObjects_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        numberOfObjects_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required bool attachments = 5;
    public static final int ATTACHMENTS_FIELD_NUMBER = 5;
    private boolean attachments_;
    /**
     * <code>required bool attachments = 5;</code>
     */
    public boolean hasAttachments() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool attachments = 5;</code>
     */
    public boolean getAttachments() {
      return attachments_;
    }

    // optional string comment = 6;
    public static final int COMMENT_FIELD_NUMBER = 6;
    private Object comment_;
    /**
     * <code>optional string comment = 6;</code>
     */
    public boolean hasComment() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string comment = 6;</code>
     */
    public String getComment() {
      Object ref = comment_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comment_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string comment = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string host = 7;
    public static final int HOST_FIELD_NUMBER = 7;
    private Object host_;
    /**
     * <code>required string host = 7;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required string host = 7;</code>
     */
    public String getHost() {
      Object ref = host_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 7;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      Object ref = host_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ctId = 8;
    public static final int CTID_FIELD_NUMBER = 8;
    private Object ctId_;
    /**
     * <code>required string ctId = 8;</code>
     */
    public boolean hasCtId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required string ctId = 8;</code>
     */
    public String getCtId() {
      Object ref = ctId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ctId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ctId = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCtIdBytes() {
      Object ref = ctId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ctId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string backupCheckSum = 9;
    public static final int BACKUPCHECKSUM_FIELD_NUMBER = 9;
    private Object backupCheckSum_;
    /**
     * <code>required string backupCheckSum = 9;</code>
     */
    public boolean hasBackupCheckSum() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required string backupCheckSum = 9;</code>
     */
    public String getBackupCheckSum() {
      Object ref = backupCheckSum_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          backupCheckSum_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string backupCheckSum = 9;</code>
     */
    public com.google.protobuf.ByteString
        getBackupCheckSumBytes() {
      Object ref = backupCheckSum_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        backupCheckSum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string jiraId = 10;
    public static final int JIRAID_FIELD_NUMBER = 10;
    private Object jiraId_;
    /**
     * <code>optional string jiraId = 10;</code>
     */
    public boolean hasJiraId() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string jiraId = 10;</code>
     */
    public String getJiraId() {
      Object ref = jiraId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jiraId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string jiraId = 10;</code>
     */
    public com.google.protobuf.ByteString
        getJiraIdBytes() {
      Object ref = jiraId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jiraId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      dataVersion_ = "";
      createDate_ = "";
      creator_ = "";
      numberOfObjects_ = "";
      attachments_ = false;
      comment_ = "";
      host_ = "";
      ctId_ = "";
      backupCheckSum_ = "";
      jiraId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDataVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreateDate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCreator()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNumberOfObjects()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttachments()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCtId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBackupCheckSum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDataVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getCreatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getNumberOfObjectsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, attachments_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getCommentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getHostBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, getCtIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getBackupCheckSumBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getJiraIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDataVersionBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCreateDateBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getCreatorBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getNumberOfObjectsBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, attachments_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getCommentBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getHostBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getCtIdBytes());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getBackupCheckSumBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getJiraIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thed.zephyr.capture.util.backup.BackupSystemInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.class, com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.Builder.class);
      }

      // Construct using com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dataVersion_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        createDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        creator_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        numberOfObjects_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        attachments_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        comment_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        ctId_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        backupCheckSum_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        jiraId_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_descriptor;
      }

      public com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo getDefaultInstanceForType() {
        return com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.getDefaultInstance();
      }

      public com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo build() {
        com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo buildPartial() {
        com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo result = new com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dataVersion_ = dataVersion_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.createDate_ = createDate_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.creator_ = creator_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.numberOfObjects_ = numberOfObjects_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.attachments_ = attachments_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.comment_ = comment_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.ctId_ = ctId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.backupCheckSum_ = backupCheckSum_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.jiraId_ = jiraId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo) {
          return mergeFrom((com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo other) {
        if (other == com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo.getDefaultInstance()) return this;
        if (other.hasDataVersion()) {
          bitField0_ |= 0x00000001;
          dataVersion_ = other.dataVersion_;
          onChanged();
        }
        if (other.hasCreateDate()) {
          bitField0_ |= 0x00000002;
          createDate_ = other.createDate_;
          onChanged();
        }
        if (other.hasCreator()) {
          bitField0_ |= 0x00000004;
          creator_ = other.creator_;
          onChanged();
        }
        if (other.hasNumberOfObjects()) {
          bitField0_ |= 0x00000008;
          numberOfObjects_ = other.numberOfObjects_;
          onChanged();
        }
        if (other.hasAttachments()) {
          setAttachments(other.getAttachments());
        }
        if (other.hasComment()) {
          bitField0_ |= 0x00000020;
          comment_ = other.comment_;
          onChanged();
        }
        if (other.hasHost()) {
          bitField0_ |= 0x00000040;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasCtId()) {
          bitField0_ |= 0x00000080;
          ctId_ = other.ctId_;
          onChanged();
        }
        if (other.hasBackupCheckSum()) {
          bitField0_ |= 0x00000100;
          backupCheckSum_ = other.backupCheckSum_;
          onChanged();
        }
        if (other.hasJiraId()) {
          bitField0_ |= 0x00000200;
          jiraId_ = other.jiraId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDataVersion()) {

          return false;
        }
        if (!hasCreateDate()) {

          return false;
        }
        if (!hasCreator()) {

          return false;
        }
        if (!hasNumberOfObjects()) {

          return false;
        }
        if (!hasAttachments()) {

          return false;
        }
        if (!hasHost()) {

          return false;
        }
        if (!hasCtId()) {

          return false;
        }
        if (!hasBackupCheckSum()) {

          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thed.zephyr.capture.util.backup.BackupSystemInfoBuffer.BackupSystemInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string dataVersion = 1;
      private Object dataVersion_ = "";
      /**
       * <code>required string dataVersion = 1;</code>
       */
      public boolean hasDataVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string dataVersion = 1;</code>
       */
      public String getDataVersion() {
        Object ref = dataVersion_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          dataVersion_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string dataVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDataVersionBytes() {
        Object ref = dataVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dataVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string dataVersion = 1;</code>
       */
      public Builder setDataVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dataVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string dataVersion = 1;</code>
       */
      public Builder clearDataVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dataVersion_ = getDefaultInstance().getDataVersion();
        onChanged();
        return this;
      }
      /**
       * <code>required string dataVersion = 1;</code>
       */
      public Builder setDataVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        dataVersion_ = value;
        onChanged();
        return this;
      }

      // required string createDate = 2;
      private Object createDate_ = "";
      /**
       * <code>required string createDate = 2;</code>
       */
      public boolean hasCreateDate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string createDate = 2;</code>
       */
      public String getCreateDate() {
        Object ref = createDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          createDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string createDate = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCreateDateBytes() {
        Object ref = createDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          createDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string createDate = 2;</code>
       */
      public Builder setCreateDate(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string createDate = 2;</code>
       */
      public Builder clearCreateDate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        createDate_ = getDefaultInstance().getCreateDate();
        onChanged();
        return this;
      }
      /**
       * <code>required string createDate = 2;</code>
       */
      public Builder setCreateDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        createDate_ = value;
        onChanged();
        return this;
      }

      // required string creator = 3;
      private Object creator_ = "";
      /**
       * <code>required string creator = 3;</code>
       */
      public boolean hasCreator() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string creator = 3;</code>
       */
      public String getCreator() {
        Object ref = creator_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          creator_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string creator = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCreatorBytes() {
        Object ref = creator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          creator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string creator = 3;</code>
       */
      public Builder setCreator(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creator_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string creator = 3;</code>
       */
      public Builder clearCreator() {
        bitField0_ = (bitField0_ & ~0x00000004);
        creator_ = getDefaultInstance().getCreator();
        onChanged();
        return this;
      }
      /**
       * <code>required string creator = 3;</code>
       */
      public Builder setCreatorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        creator_ = value;
        onChanged();
        return this;
      }

      // required string numberOfObjects = 4;
      private Object numberOfObjects_ = "";
      /**
       * <code>required string numberOfObjects = 4;</code>
       */
      public boolean hasNumberOfObjects() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string numberOfObjects = 4;</code>
       */
      public String getNumberOfObjects() {
        Object ref = numberOfObjects_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          numberOfObjects_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string numberOfObjects = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNumberOfObjectsBytes() {
        Object ref = numberOfObjects_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          numberOfObjects_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string numberOfObjects = 4;</code>
       */
      public Builder setNumberOfObjects(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        numberOfObjects_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string numberOfObjects = 4;</code>
       */
      public Builder clearNumberOfObjects() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numberOfObjects_ = getDefaultInstance().getNumberOfObjects();
        onChanged();
        return this;
      }
      /**
       * <code>required string numberOfObjects = 4;</code>
       */
      public Builder setNumberOfObjectsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        numberOfObjects_ = value;
        onChanged();
        return this;
      }

      // required bool attachments = 5;
      private boolean attachments_ ;
      /**
       * <code>required bool attachments = 5;</code>
       */
      public boolean hasAttachments() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool attachments = 5;</code>
       */
      public boolean getAttachments() {
        return attachments_;
      }
      /**
       * <code>required bool attachments = 5;</code>
       */
      public Builder setAttachments(boolean value) {
        bitField0_ |= 0x00000010;
        attachments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool attachments = 5;</code>
       */
      public Builder clearAttachments() {
        bitField0_ = (bitField0_ & ~0x00000010);
        attachments_ = false;
        onChanged();
        return this;
      }

      // optional string comment = 6;
      private Object comment_ = "";
      /**
       * <code>optional string comment = 6;</code>
       */
      public boolean hasComment() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string comment = 6;</code>
       */
      public String getComment() {
        Object ref = comment_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          comment_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string comment = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCommentBytes() {
        Object ref = comment_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          comment_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string comment = 6;</code>
       */
      public Builder setComment(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string comment = 6;</code>
       */
      public Builder clearComment() {
        bitField0_ = (bitField0_ & ~0x00000020);
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      /**
       * <code>optional string comment = 6;</code>
       */
      public Builder setCommentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        comment_ = value;
        onChanged();
        return this;
      }

      // required string host = 7;
      private Object host_ = "";
      /**
       * <code>required string host = 7;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required string host = 7;</code>
       */
      public String getHost() {
        Object ref = host_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string host = 7;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 7;</code>
       */
      public Builder setHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 7;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000040);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 7;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        host_ = value;
        onChanged();
        return this;
      }

      // required string ctId = 8;
      private Object ctId_ = "";
      /**
       * <code>required string ctId = 8;</code>
       */
      public boolean hasCtId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required string ctId = 8;</code>
       */
      public String getCtId() {
        Object ref = ctId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ctId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string ctId = 8;</code>
       */
      public com.google.protobuf.ByteString
          getCtIdBytes() {
        Object ref = ctId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ctId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ctId = 8;</code>
       */
      public Builder setCtId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ctId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ctId = 8;</code>
       */
      public Builder clearCtId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        ctId_ = getDefaultInstance().getCtId();
        onChanged();
        return this;
      }
      /**
       * <code>required string ctId = 8;</code>
       */
      public Builder setCtIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        ctId_ = value;
        onChanged();
        return this;
      }

      // required string backupCheckSum = 9;
      private Object backupCheckSum_ = "";
      /**
       * <code>required string backupCheckSum = 9;</code>
       */
      public boolean hasBackupCheckSum() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required string backupCheckSum = 9;</code>
       */
      public String getBackupCheckSum() {
        Object ref = backupCheckSum_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          backupCheckSum_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string backupCheckSum = 9;</code>
       */
      public com.google.protobuf.ByteString
          getBackupCheckSumBytes() {
        Object ref = backupCheckSum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          backupCheckSum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string backupCheckSum = 9;</code>
       */
      public Builder setBackupCheckSum(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        backupCheckSum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string backupCheckSum = 9;</code>
       */
      public Builder clearBackupCheckSum() {
        bitField0_ = (bitField0_ & ~0x00000100);
        backupCheckSum_ = getDefaultInstance().getBackupCheckSum();
        onChanged();
        return this;
      }
      /**
       * <code>required string backupCheckSum = 9;</code>
       */
      public Builder setBackupCheckSumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        backupCheckSum_ = value;
        onChanged();
        return this;
      }

      // optional string jiraId = 10;
      private Object jiraId_ = "";
      /**
       * <code>optional string jiraId = 10;</code>
       */
      public boolean hasJiraId() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string jiraId = 10;</code>
       */
      public String getJiraId() {
        Object ref = jiraId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          jiraId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string jiraId = 10;</code>
       */
      public com.google.protobuf.ByteString
          getJiraIdBytes() {
        Object ref = jiraId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jiraId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string jiraId = 10;</code>
       */
      public Builder setJiraId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        jiraId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string jiraId = 10;</code>
       */
      public Builder clearJiraId() {
        bitField0_ = (bitField0_ & ~0x00000200);
        jiraId_ = getDefaultInstance().getJiraId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string jiraId = 10;</code>
       */
      public Builder setJiraIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        jiraId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.thed.zephyr.capture.util.backup.BackupSystemInfo)
    }

    static {
      defaultInstance = new BackupSystemInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.thed.zephyr.capture.util.backup.BackupSystemInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026BackupSystemInfo.proto\022\034com.thed.zephy" +
      "r.connect.util\"\317\001\n\020BackupSystemInfo\022\023\n\013d" +
      "ataVersion\030\001 \002(\t\022\022\n\ncreateDate\030\002 \002(\t\022\017\n\007" +
      "creator\030\003 \002(\t\022\027\n\017numberOfObjects\030\004 \002(\t\022\023" +
      "\n\013attachments\030\005 \002(\010\022\017\n\007comment\030\006 \001(\t\022\014\n\004" +
      "host\030\007 \002(\t\022\014\n\004ctId\030\010 \002(\t\022\026\n\016backupCheckS" +
      "um\030\t \002(\t\022\016\n\006jiraId\030\n \001(\tB6\n\034com.thed.zep" +
      "hyr.connect.utilB\026BackupSystemInfoBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_thed_zephyr_connect_util_BackupSystemInfo_descriptor,
              new String[] { "DataVersion", "CreateDate", "Creator", "NumberOfObjects", "Attachments", "Comment", "Host", "CtId", "BackupCheckSum", "JiraId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
