// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BackupBuffer.proto

package com.thed.zephyr.capture.util.backup;

public final class BackupBuffer {
  private BackupBuffer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BackupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.thed.zephyr.capture.util.backup.Backup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    java.util.List<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object>
        getObjectsList();
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object getObjects(int index);
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    int getObjectsCount();
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    java.util.List<? extends com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder>
        getObjectsOrBuilderList();
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder getObjectsOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code com.thed.zephyr.capture.util.backup.Backup}
   */
  public static final class Backup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.thed.zephyr.capture.util.backup.Backup)
      BackupOrBuilder {
    // Use Backup.newBuilder() to construct.
    private Backup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Backup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Backup defaultInstance;
    public static Backup getDefaultInstance() {
      return defaultInstance;
    }

    public Backup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Backup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                objects_ = new java.util.ArrayList<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object>();
                mutable_bitField0_ |= 0x00000001;
              }
              objects_.add(input.readMessage(com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          objects_ = java.util.Collections.unmodifiableList(objects_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.class, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Builder.class);
    }

    public static com.google.protobuf.Parser<Backup> PARSER =
        new com.google.protobuf.AbstractParser<Backup>() {
      public Backup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Backup(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Backup> getParserForType() {
      return PARSER;
    }

    public interface ObjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.thed.zephyr.capture.util.backup.Backup.Object)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string entity = 1;</code>
       */
      boolean hasEntity();
      /**
       * <code>required string entity = 1;</code>
       */
      String getEntity();
      /**
       * <code>required string entity = 1;</code>
       */
      com.google.protobuf.ByteString
          getEntityBytes();

      /**
       * <code>required string key = 2;</code>
       */
      boolean hasKey();
      /**
       * <code>required string key = 2;</code>
       */
      String getKey();
      /**
       * <code>required string key = 2;</code>
       */
      com.google.protobuf.ByteString
          getKeyBytes();

      /**
       * <code>required string jsonString = 3;</code>
       */
      boolean hasJsonString();
      /**
       * <code>required string jsonString = 3;</code>
       */
      String getJsonString();
      /**
       * <code>required string jsonString = 3;</code>
       */
      com.google.protobuf.ByteString
          getJsonStringBytes();

      /**
       * <code>optional string entityType = 4;</code>
       */
      boolean hasEntityType();
      /**
       * <code>optional string entityType = 4;</code>
       */
      String getEntityType();
      /**
       * <code>optional string entityType = 4;</code>
       */
      com.google.protobuf.ByteString
          getEntityTypeBytes();
    }
    /**
     * Protobuf type {@code com.thed.zephyr.capture.util.backup.Backup.Object}
     */
    public static final class Object extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:com.thed.zephyr.capture.util.backup.Backup.Object)
        ObjectOrBuilder {
      // Use Object.newBuilder() to construct.
      private Object(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Object(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Object defaultInstance;
      public static Object getDefaultInstance() {
        return defaultInstance;
      }

      public Object getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Object(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                entity_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                key_ = bs;
                break;
              }
              case 26: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000004;
                jsonString_ = bs;
                break;
              }
              case 34: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000008;
                entityType_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_Object_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_Object_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.class, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder.class);
      }

      public static com.google.protobuf.Parser<Object> PARSER =
          new com.google.protobuf.AbstractParser<Object>() {
        public Object parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Object(input, extensionRegistry);
        }
      };

      @Override
      public com.google.protobuf.Parser<Object> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ENTITY_FIELD_NUMBER = 1;
      private java.lang.Object entity_;
      /**
       * <code>required string entity = 1;</code>
       */
      public boolean hasEntity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string entity = 1;</code>
       */
      public String getEntity() {
        java.lang.Object ref = entity_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entity_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string entity = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEntityBytes() {
        java.lang.Object ref = entity_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          entity_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int KEY_FIELD_NUMBER = 2;
      private java.lang.Object key_;
      /**
       * <code>required string key = 2;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string key = 2;</code>
       */
      public String getKey() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string key = 2;</code>
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int JSONSTRING_FIELD_NUMBER = 3;
      private java.lang.Object jsonString_;
      /**
       * <code>required string jsonString = 3;</code>
       */
      public boolean hasJsonString() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string jsonString = 3;</code>
       */
      public String getJsonString() {
        java.lang.Object ref = jsonString_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jsonString_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string jsonString = 3;</code>
       */
      public com.google.protobuf.ByteString
          getJsonStringBytes() {
        java.lang.Object ref = jsonString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jsonString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int entityType_FIELD_NUMBER = 4;
      private java.lang.Object entityType_;
      /**
       * <code>optional string entityType = 4;</code>
       */
      public boolean hasEntityType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string entityType = 4;</code>
       */
      public String getEntityType() {
        java.lang.Object ref = entityType_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            entityType_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string entityType = 4;</code>
       */
      public com.google.protobuf.ByteString
          getEntityTypeBytes() {
        java.lang.Object ref = entityType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          entityType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        entity_ = "";
        key_ = "";
        jsonString_ = "";
        entityType_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasEntity()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasKey()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasJsonString()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getEntityBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getKeyBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getJsonStringBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getEntityTypeBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getEntityBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getKeyBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getJsonStringBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getEntityTypeBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.thed.zephyr.capture.util.backup.Backup.Object}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.thed.zephyr.capture.util.backup.Backup.Object)
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_Object_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_Object_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.class, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder.class);
        }

        // Construct using com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          entity_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          key_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          jsonString_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          entityType_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_Object_descriptor;
        }

        public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object getDefaultInstanceForType() {
          return com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.getDefaultInstance();
        }

        public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object build() {
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object buildPartial() {
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object result = new com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.entity_ = entity_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.key_ = key_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.jsonString_ = jsonString_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.entityType_ = entityType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object) {
            return mergeFrom((com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object other) {
          if (other == com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.getDefaultInstance()) return this;
          if (other.hasEntity()) {
            bitField0_ |= 0x00000001;
            entity_ = other.entity_;
            onChanged();
          }
          if (other.hasKey()) {
            bitField0_ |= 0x00000002;
            key_ = other.key_;
            onChanged();
          }
          if (other.hasJsonString()) {
            bitField0_ |= 0x00000004;
            jsonString_ = other.jsonString_;
            onChanged();
          }
          if (other.hasEntityType()) {
            bitField0_ |= 0x00000008;
            entityType_ = other.entityType_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasEntity()) {

            return false;
          }
          if (!hasKey()) {

            return false;
          }
          if (!hasJsonString()) {

            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object entity_ = "";
        /**
         * <code>required string entity = 1;</code>
         */
        public boolean hasEntity() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string entity = 1;</code>
         */
        public String getEntity() {
          java.lang.Object ref = entity_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              entity_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string entity = 1;</code>
         */
        public com.google.protobuf.ByteString
            getEntityBytes() {
          java.lang.Object ref = entity_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            entity_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string entity = 1;</code>
         */
        public Builder setEntity(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          entity_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string entity = 1;</code>
         */
        public Builder clearEntity() {
          bitField0_ = (bitField0_ & ~0x00000001);
          entity_ = getDefaultInstance().getEntity();
          onChanged();
          return this;
        }
        /**
         * <code>required string entity = 1;</code>
         */
        public Builder setEntityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          entity_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object key_ = "";
        /**
         * <code>required string key = 2;</code>
         */
        public boolean hasKey() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string key = 2;</code>
         */
        public String getKey() {
          java.lang.Object ref = key_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              key_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string key = 2;</code>
         */
        public com.google.protobuf.ByteString
            getKeyBytes() {
          java.lang.Object ref = key_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            key_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string key = 2;</code>
         */
        public Builder setKey(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          key_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 2;</code>
         */
        public Builder clearKey() {
          bitField0_ = (bitField0_ & ~0x00000002);
          key_ = getDefaultInstance().getKey();
          onChanged();
          return this;
        }
        /**
         * <code>required string key = 2;</code>
         */
        public Builder setKeyBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          key_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object jsonString_ = "";
        /**
         * <code>required string jsonString = 3;</code>
         */
        public boolean hasJsonString() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>required string jsonString = 3;</code>
         */
        public String getJsonString() {
          java.lang.Object ref = jsonString_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              jsonString_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>required string jsonString = 3;</code>
         */
        public com.google.protobuf.ByteString
            getJsonStringBytes() {
          java.lang.Object ref = jsonString_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            jsonString_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string jsonString = 3;</code>
         */
        public Builder setJsonString(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          jsonString_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string jsonString = 3;</code>
         */
        public Builder clearJsonString() {
          bitField0_ = (bitField0_ & ~0x00000004);
          jsonString_ = getDefaultInstance().getJsonString();
          onChanged();
          return this;
        }
        /**
         * <code>required string jsonString = 3;</code>
         */
        public Builder setJsonStringBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          jsonString_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object entityType_ = "";
        /**
         * <code>optional string entityType = 4;</code>
         */
        public boolean hasEntityType() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional string entityType = 4;</code>
         */
        public String getEntityType() {
          java.lang.Object ref = entityType_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              entityType_ = s;
            }
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>optional string entityType = 4;</code>
         */
        public com.google.protobuf.ByteString
            getEntityTypeBytes() {
          java.lang.Object ref = entityType_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            entityType_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string entityType = 4;</code>
         */
        public Builder setEntityType(
            String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          entityType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string entityType = 4;</code>
         */
        public Builder clearEntityType() {
          bitField0_ = (bitField0_ & ~0x00000008);
          entityType_ = getDefaultInstance().getEntityType();
          onChanged();
          return this;
        }
        /**
         * <code>optional string entityType = 4;</code>
         */
        public Builder setEntityTypeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          entityType_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.thed.zephyr.capture.util.backup.Backup.Object)
      }

      static {
        defaultInstance = new Object(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.thed.zephyr.capture.util.backup.Backup.Object)
    }

    public static final int OBJECTS_FIELD_NUMBER = 1;
    private java.util.List<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object> objects_;
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    public java.util.List<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object> getObjectsList() {
      return objects_;
    }
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    public java.util.List<? extends com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder>
        getObjectsOrBuilderList() {
      return objects_;
    }
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    public int getObjectsCount() {
      return objects_.size();
    }
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object getObjects(int index) {
      return objects_.get(index);
    }
    /**
     * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
     */
    public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder getObjectsOrBuilder(
        int index) {
      return objects_.get(index);
    }

    private void initFields() {
      objects_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getObjectsCount(); i++) {
        if (!getObjects(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < objects_.size(); i++) {
        output.writeMessage(1, objects_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < objects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, objects_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.thed.zephyr.capture.util.backup.BackupBuffer.Backup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.thed.zephyr.capture.util.backup.Backup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.thed.zephyr.capture.util.backup.Backup)
        com.thed.zephyr.capture.util.backup.BackupBuffer.BackupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.class, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Builder.class);
      }

      // Construct using com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObjectsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (objectsBuilder_ == null) {
          objects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          objectsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.thed.zephyr.capture.util.backup.BackupBuffer.internal_static_com_thed_zephyr_connect_util_Backup_descriptor;
      }

      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup getDefaultInstanceForType() {
        return com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.getDefaultInstance();
      }

      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup build() {
        com.thed.zephyr.capture.util.backup.BackupBuffer.Backup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup buildPartial() {
        com.thed.zephyr.capture.util.backup.BackupBuffer.Backup result = new com.thed.zephyr.capture.util.backup.BackupBuffer.Backup(this);
        int from_bitField0_ = bitField0_;
        if (objectsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            objects_ = java.util.Collections.unmodifiableList(objects_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.objects_ = objects_;
        } else {
          result.objects_ = objectsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.thed.zephyr.capture.util.backup.BackupBuffer.Backup) {
          return mergeFrom((com.thed.zephyr.capture.util.backup.BackupBuffer.Backup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.thed.zephyr.capture.util.backup.BackupBuffer.Backup other) {
        if (other == com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.getDefaultInstance()) return this;
        if (objectsBuilder_ == null) {
          if (!other.objects_.isEmpty()) {
            if (objects_.isEmpty()) {
              objects_ = other.objects_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureObjectsIsMutable();
              objects_.addAll(other.objects_);
            }
            onChanged();
          }
        } else {
          if (!other.objects_.isEmpty()) {
            if (objectsBuilder_.isEmpty()) {
              objectsBuilder_.dispose();
              objectsBuilder_ = null;
              objects_ = other.objects_;
              bitField0_ = (bitField0_ & ~0x00000001);
              objectsBuilder_ =
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getObjectsFieldBuilder() : null;
            } else {
              objectsBuilder_.addAllMessages(other.objects_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getObjectsCount(); i++) {
          if (!getObjects(i).isInitialized()) {

            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.thed.zephyr.capture.util.backup.BackupBuffer.Backup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.thed.zephyr.capture.util.backup.BackupBuffer.Backup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object> objects_ =
        java.util.Collections.emptyList();
      private void ensureObjectsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          objects_ = new java.util.ArrayList<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object>(objects_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder> objectsBuilder_;

      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public java.util.List<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object> getObjectsList() {
        if (objectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(objects_);
        } else {
          return objectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public int getObjectsCount() {
        if (objectsBuilder_ == null) {
          return objects_.size();
        } else {
          return objectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object getObjects(int index) {
        if (objectsBuilder_ == null) {
          return objects_.get(index);
        } else {
          return objectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder setObjects(
          int index, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.set(index, value);
          onChanged();
        } else {
          objectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder setObjects(
          int index, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.set(index, builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder addObjects(com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.add(value);
          onChanged();
        } else {
          objectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder addObjects(
          int index, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.add(index, value);
          onChanged();
        } else {
          objectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder addObjects(
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.add(builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder addObjects(
          int index, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.add(index, builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder addAllObjects(
          Iterable<? extends com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object> values) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, objects_);
          onChanged();
        } else {
          objectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder clearObjects() {
        if (objectsBuilder_ == null) {
          objects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          objectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public Builder removeObjects(int index) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.remove(index);
          onChanged();
        } else {
          objectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder getObjectsBuilder(
          int index) {
        return getObjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder getObjectsOrBuilder(
          int index) {
        if (objectsBuilder_ == null) {
          return objects_.get(index);  } else {
          return objectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public java.util.List<? extends com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder>
           getObjectsOrBuilderList() {
        if (objectsBuilder_ != null) {
          return objectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(objects_);
        }
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder addObjectsBuilder() {
        return getObjectsFieldBuilder().addBuilder(
            com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.getDefaultInstance());
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder addObjectsBuilder(
          int index) {
        return getObjectsFieldBuilder().addBuilder(
            index, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.getDefaultInstance());
      }
      /**
       * <code>repeated .com.thed.zephyr.capture.util.backup.Backup.Object objects = 1;</code>
       */
      public java.util.List<com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder>
           getObjectsBuilderList() {
        return getObjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder>
          getObjectsFieldBuilder() {
        if (objectsBuilder_ == null) {
          objectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.Object.Builder, com.thed.zephyr.capture.util.backup.BackupBuffer.Backup.ObjectOrBuilder>(
                  objects_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          objects_ = null;
        }
        return objectsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.thed.zephyr.capture.util.backup.Backup)
    }

    static {
      defaultInstance = new Backup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.thed.zephyr.capture.util.backup.Backup)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thed_zephyr_connect_util_Backup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_thed_zephyr_connect_util_Backup_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_thed_zephyr_connect_util_Backup_Object_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_thed_zephyr_connect_util_Backup_Object_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022BackupBuffer.proto\022\034com.thed.zephyr.co" +
      "nnect.util\"\225\001\n\006Backup\022<\n\007objects\030\001 \003(\0132+" +
      ".com.thed.zephyr.capture.util.backup.Backup.Obj" +
      "ect\032M\n\006Object\022\016\n\006entity\030\001 \002(\t\022\013\n\003key\030\002 \002" +
      "(\t\022\022\n\njsonString\030\003 \002(\t\022\022\n\nentityType\030\004 \001" +
      "(\tB,\n\034com.thed.zephyr.capture.util.backupB\014Back" +
      "upBuffer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_thed_zephyr_connect_util_Backup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_thed_zephyr_connect_util_Backup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_thed_zephyr_connect_util_Backup_descriptor,
        new String[] { "Objects", });
    internal_static_com_thed_zephyr_connect_util_Backup_Object_descriptor =
      internal_static_com_thed_zephyr_connect_util_Backup_descriptor.getNestedTypes().get(0);
    internal_static_com_thed_zephyr_connect_util_Backup_Object_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_thed_zephyr_connect_util_Backup_Object_descriptor,
        new String[] { "Entity", "Key", "JsonString", "EntityType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
