package com.thed.zephyr.capture.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.thed.zephyr.capture.service.db.converter.DateTimeTypeConverter;
import com.thed.zephyr.capture.service.db.converter.ResolutionTypeConverter;
import com.thed.zephyr.capture.service.db.converter.TagSetConverter;
import com.thed.zephyr.capture.util.ApplicationConstants;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.joda.time.DateTime;
import org.joda.time.format.ISODateTimeFormat;
import org.springframework.data.annotation.Id;

import java.util.Collections;
import java.util.Set;

/**
 * Created by aliakseimatsarski on 8/14/17.
 */
@DynamoDBTable(tableName = ApplicationConstants.NOTE_TABLE_NAME)
final public class Note {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = ApplicationConstants.GSI_CT_ID_SESSION_ID)
    private String ctId;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = ApplicationConstants.GSI_CT_ID_SESSION_ID)
    private String sessionId;

    private Long projectId;

    @DynamoDBTypeConverted(converter = DateTimeTypeConverter.class)
    private DateTime createdTime;

    private String author;

    /**
     * Raw data of the note itself
     */
    private String noteData;

    /**
     * Resolution for this note
     */
    @DynamoDBTypeConverted(converter = ResolutionTypeConverter.class)
    private Resolution resolutionState;

    /**
     * List of tags for this note.
     * A note may have multiple tags, example: "#question #wtf #performance Why does this take 10 seconds?"
     */
    @DynamoDBIgnore
    private Set<Tag> tags;

    /**
     * <p>
     * Notes without tags are NON_ACTIONABLE.
     * </p>
     * <p>
     * Notes with tags start in INITIAL state, and move to COMPLETED (and potentially back again).
     * INVALID is currently unused as of 1.4.
     * </p>
     */
    public enum Resolution {
        NON_ACTIONABLE, INITIAL, COMPLETED, INVALID
    }

    public Note() {
    }

    /**
     * Create a new note.
     * The tags are extracted from the note data.
     *
     * @param id              ID of this note
     * @param sessionId       Session ID of the related session
     * @param createdTime     time the note is created
     * @param author  username of the author creating the note
     * @param noteData        not data
     * @param resolutionState resolution for the note
     */
    public Note(String id, String sessionId, String ctId, DateTime createdTime, String author, String noteData, Set<Tag> tags, Resolution resolutionState) {
        this.id = id;
        this.sessionId = sessionId;
        this.ctId = ctId;
        this.createdTime = createdTime;
        this.author = author;
        this.noteData = noteData;
        this.tags = tags;

        // If we have tags, take the passed resolutionState (or make it INITIAL if it was NON_ACTIONABLE)
        // Otherwise with no tags, it's NON_ACTIONABLE. And that is non-negotiable.
        if (this.tags.size() > 0) {
            if (Resolution.NON_ACTIONABLE.equals(resolutionState)) {
                this.resolutionState = Resolution.INITIAL;
            } else {
                this.resolutionState = resolutionState;
            }
        } else {
            this.resolutionState = Resolution.NON_ACTIONABLE;
        }
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCtId() {
        return ctId;
    }

    public void setCtId(String ctId) {
        this.ctId = ctId;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public DateTime getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(DateTime createdTime) {
        this.createdTime = createdTime;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getNoteData() {
        return noteData;
    }

    public void setNoteData(String noteData) {
        this.noteData = noteData;
    }

    public Resolution getResolutionState() {
        return resolutionState;
    }

    public void setResolutionState(Resolution resolutionState) {
        this.resolutionState = resolutionState;
    }

    public Set<Tag> getTags() {
        return tags;
    }

    public void setTags(Set<Tag> tags) {
        this.tags = tags;
    }

    public Long getProjectId() {
        return projectId;
    }

    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }

    public JsonNode toJson() {
        ObjectMapper om = new ObjectMapper();
        JsonNode jsonNode = om.convertValue(this, JsonNode.class);

        return jsonNode;
    }
}
