package com.thed.zephyr.capture.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.thed.zephyr.capture.service.db.converter.DateTimeTypeConverter;
import com.thed.zephyr.capture.util.ApplicationConstants;
import org.joda.time.DateTime;
import org.springframework.data.annotation.Id;

/**
 * Created by aliakseimatsarski on 8/15/17.
 */
@DynamoDBTable(tableName = ApplicationConstants.SESSION_ACTIVITY_TABLE_NAME)
abstract public class SessionActivity {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = ApplicationConstants.GSI_SESSIONID_TIMESTAMP)
    private String sessionId;

    private String clientKey;

    @DynamoDBIndexRangeKey(globalSecondaryIndexName = ApplicationConstants.GSI_SESSIONID_TIMESTAMP)
    @DynamoDBTypeConverted(converter = DateTimeTypeConverter.class)
    private DateTime timestamp;

    private String user;

    private String avatarUrl;

    private String clazz;

    public SessionActivity() {
    }

    public SessionActivity(String sessionId, String clientKey, DateTime timestamp, String user, String avatarUrl) {
        this.sessionId = sessionId;
        this.clientKey = clientKey;
        this.timestamp = timestamp;
        this.user = user;
        this.avatarUrl = avatarUrl;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getClientKey() {
        return clientKey;
    }

    public void setClientKey(String clientKey) {
        this.clientKey = clientKey;
    }

    public DateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(DateTime time) {
        this.timestamp = time;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getClazz() {
        return this.getClass().getCanonicalName();
    }

    public void setClazz(String clazz) {
        this.clazz = this.getClass().getCanonicalName();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        SessionActivity that = (SessionActivity) o;

        if (timestamp != null ? !timestamp.equals(that.timestamp) : that.timestamp != null) {
            return false;
        }
        if (user != null ? !user.equals(that.user) : that.user != null) {
            return false;
        }

        return true;
    }

    @Override
    public int hashCode() {
        int result = timestamp != null ? timestamp.hashCode() : 0;
        result = 31 * result + (user != null ? user.hashCode() : 0);
        return result;
    }
}
