package com.thed.zephyr.capture.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.thed.zephyr.capture.util.ApplicationConstants;
import org.springframework.data.annotation.Id;

/**
 * 
 * @author Venkatareddy on 08/24/17.
 *
 */
@DynamoDBTable(tableName = ApplicationConstants.VARIABLE_TABLE_NAME)
public class Variable {

    @Id
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = ApplicationConstants.GSI_CT_ID_OWNER_NAME)
    private String ctId;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = ApplicationConstants.GSI_CT_ID_OWNER_NAME)
    private String ownerName;
    private String name;
    private String value;

    public Variable() {
    }

    public Variable(String ctId, String ownerName, String name, String value) {
        this.ctId = ctId;
        this.ownerName = ownerName;
        this.name = name;
        this.value = value;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCtId() {
        return ctId;
    }

    public void setCtId(String ctId) {
        this.ctId = ctId;
    }

    public String getOwnerName() {
        return ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Variable variable = (Variable) o;

        if (!id.equals(variable.id)) return false;
        if (!ctId.equals(variable.ctId)) return false;
        if (!ownerName.equals(variable.ownerName)) return false;
        if (!name.equals(variable.name)) return false;
        return value.equals(variable.value);
    }

    @Override
    public int hashCode() {
        int result = id.hashCode();
        result = 31 * result + ctId.hashCode();
        result = 31 * result + ownerName.hashCode();
        result = 31 * result + name.hashCode();
        result = 31 * result + value.hashCode();
        return result;
    }

    @Override
    public String toString() {
        return "Variable{" +
                "id='" + id + '\'' +
                ", ctId='" + ctId + '\'' +
                ", ownerName='" + ownerName + '\'' +
                ", name='" + name + '\'' +
                ", value='" + value + '\'' +
                '}';
    }
}

